name: Deploy to ec2 instance

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ vars.development }}
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/
            sudo rm -rf cloudwatch-logs-vue
            sudo rm -rf /var/www/html/*
            sudo git clone https://github.com/TudorIonutElian/cloudwatch-logs-vue.git
            cd cloudwatch-logs-vue
            sudo npm install
            sudo npm run build
            cd /var/www/
            sudo mkdir -p html
            sudo mv /var/www/cloudwatch-logs-vue/.htaccess  /var/www/cloudwatch-logs-vue/dist/
            sudo mv /var/www/cloudwatch-logs-vue/dist/* /var/www/html/
            cd ../
            sudo rm -rf cloudwatch-logs-vue
            export default API_LOGS_ENDPOINT = ${{vars.API_LOGS_ENDPOINT}}